<script setup>
import { computed, ref } from 'vue'
import yaml from 'js-yaml'
import CodeBlock from '../components/CodeBlock.vue'
const specText=ref(''), spec=ref(null), error=ref(''), selected=ref(null), values=ref({})
function parse(){error.value=''; try{spec.value=yaml.load(specText.value); selected.value=null}catch(e){error.value=e.message}}
const endpoints=computed(()=>{ if(!spec.value?.paths)return[]; const out=[]; for(const [path,obj] of Object.entries(spec.value.paths)) for(const [method,op] of Object.entries(obj)) if(['get','post','put','patch','delete','head','options'].includes(method)) out.push({path,method:method.toUpperCase(),...op}); return out })
function choose(ep){selected.value=ep;values.value={};(ep.parameters||[]).forEach(p=>values.value[p.name]=p.schema?.default??'')}
const preview=computed(()=>{if(!selected.value)return''; let path=selected.value.path;(selected.value.parameters||[]).filter(p=>p.in==='path').forEach(p=>path=path.replace(`{${p.name}}`,encodeURIComponent(values.value[p.name]||`{${p.name}}`))); const base=spec.value?.servers?.[0]?.url||'https://api.example.com'; const u=new URL(path,base.endsWith('/')?base:base+'/'); (selected.value.parameters||[]).filter(p=>p.in==='query'&&values.value[p.name]).forEach(p=>u.searchParams.set(p.name,values.value[p.name])); let s=`curl -X ${selected.value.method} '${u.toString()}'`; (selected.value.parameters||[]).filter(p=>p.in==='header'&&values.value[p.name]).forEach(p=>s+=` \\\n  -H '${p.name}: ${values.value[p.name]}'`); return s})
</script>
<template><section class="mx-auto max-w-7xl px-5 py-10"><div class="mb-8"><div class="badge">OpenAPI</div><h1 class="mt-3 text-3xl font-bold">Endpoint Assist</h1><p class="mt-2 text-slate-400">Paste JSON or YAML. MDH-API turns the spec into fill-in-the-blank endpoints.</p></div><div class="grid gap-6 lg:grid-cols-2"><div class="panel p-5"><textarea v-model="specText" class="input mono min-h-[420px]" placeholder="Paste OpenAPI 3.x or Swagger JSON/YAML here…"></textarea><div v-if="error" class="mt-3 text-sm text-red-300">{{error}}</div><button @click="parse" class="btn-primary mt-3">Analyze spec</button></div><div class="panel p-5"><h2 class="mb-4 font-bold">Endpoints <span class="text-slate-500">{{endpoints.length}}</span></h2><div class="max-h-[470px] overflow-auto"><button v-for="ep in endpoints" :key="ep.method+ep.path" @click="choose(ep)" class="mb-2 flex w-full items-center gap-3 rounded-sm border border-white/5 p-3 text-left hover:border-cyan-300/20 hover:bg-white/5"><span class="w-16 text-xs font-bold text-cyan-300">{{ep.method}}</span><span class="mono text-sm">{{ep.path}}</span></button><div v-if="!endpoints.length" class="p-10 text-center text-sm text-slate-500">Import a spec to browse endpoints.</div></div></div></div>
<div v-if="selected" class="panel mt-6 p-5"><div class="flex items-center gap-3"><span class="badge">{{selected.method}}</span><h2 class="mono font-bold">{{selected.path}}</h2></div><p v-if="selected.summary" class="mt-2 text-sm text-slate-400">{{selected.summary}}</p><div class="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 class="mb-3 font-semibold">Requirements</h3><div v-for="p in selected.parameters||[]" :key="p.in+p.name" class="mb-3"><label class="mb-1 flex gap-2 text-xs text-slate-400"><span>{{p.name}}</span><span class="text-slate-600">{{p.in}}</span><span v-if="p.required" class="text-amber-300">required</span></label><input v-model="values[p.name]" class="input" :placeholder="p.schema?.type||'value'"></div><div v-if="!(selected.parameters||[]).length" class="text-sm text-slate-500">No parameters declared for this operation.</div></div><div><h3 class="mb-3 font-semibold">Generated cURL</h3><CodeBlock :code="preview"/></div></div></div></section></template>
